name: Deploy to Surge

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Surge
        run: npm install --global surge
      - name: Deploy to Surge
        run: surge ./dist exciting-clocks.surge.sh
